from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from src.agents.revenueos_orchestrator import (
    run_revenueos
)

from src.agents.review_controller import (
    process_review_decision
)

from src.agents.case_manager import (
    get_all_cases
)


# ==========================================================
# FASTAPI APPLICATION
# ==========================================================

app = FastAPI(
    title="RevenueOS-AI",
    description="Autonomous Merchant Risk Investigation API",
    version="1.0.0"
)


# ==========================================================
# REVIEW REQUEST MODEL
# ==========================================================

class ReviewDecisionRequest(BaseModel):

    merchant_id: str

    review_id: str

    reviewer: str

    comments: str = ""


# ==========================================================
# ROOT ENDPOINT
# ==========================================================

@app.get("/")
def root():

    return {
        "system": "RevenueOS-AI",
        "status": "running",
        "message":
            "Autonomous Merchant Risk Investigation API"
    }


# ==========================================================
# HEALTH CHECK
# ==========================================================

@app.get("/health")
def health():

    return {
        "status": "healthy"
    }


# ==========================================================
# REASON FALLBACK
# ==========================================================

def generate_reason(result):

    decision = str(
        result.get("decision", "")
    ).strip().upper()

    risk_score = result.get(
        "risk_score",
        0
    )

    risk_category = result.get(
        "risk_category",
        "Unknown"
    )

    failure_rate = result.get(
        "failure_rate",
        0
    )

    try:

        risk_score = float(
            risk_score
        )

    except (
        TypeError,
        ValueError
    ):

        risk_score = 0.0

    try:

        failure_rate = float(
            failure_rate
        )

    except (
        TypeError,
        ValueError
    ):

        failure_rate = 0.0

    failure_rate_pct = (
        failure_rate * 100
    )


    if decision == "INVESTIGATE":

        if risk_score >= 90:

            return (
                "Very high merchant risk detected. "
                "Automated investigation is required "
                "to determine the underlying cause."
            )

        elif failure_rate_pct >= 5:

            return (
                "Elevated transaction failure behaviour "
                "detected. Merchant requires automated "
                "investigation."
            )

        elif risk_category.lower() == "high":

            return (
                "High merchant risk detected. "
                "Automated investigation is required."
            )

        return (
            "Merchant risk indicators require "
            "automated investigation."
        )


    if decision == "ESCALATE":

        return (
            "Critical merchant risk detected. "
            "Immediate human review and escalation "
            "are required."
        )


    if decision == "MONITOR":

        if failure_rate_pct >= 5:

            return (
                f"Merchant has a {failure_rate_pct:.2f}% "
                "transaction failure rate. Risk is not "
                "critical, but the elevated failure "
                "behaviour requires continuous monitoring."
            )

        if risk_score >= 30:

            return (
                f"Merchant has a risk score of "
                f"{risk_score:.2f} and is classified as "
                f"{risk_category}. Continuous monitoring "
                "is recommended."
            )

        return (
            "Merchant risk is moderate and does not "
            "currently require automated investigation. "
            "Continuous monitoring is recommended."
        )


    if decision == "NO_ACTION":

        return (
            "Merchant risk and transaction behaviour "
            "are within the normal operating range. "
            "No immediate action is required."
        )


    if decision == "ERROR":

        return (
            "The RevenueOS-AI agent encountered an error "
            "while processing this merchant."
        )


    if decision == "UNKNOWN":

        return (
            "The merchant could not be evaluated because "
            "the merchant record or decision was unavailable."
        )


    return (
        "Decision generated by RevenueOS-AI based on "
        "available merchant risk indicators."
    )


# ==========================================================
# NORMALIZE AGENT RESULT
# ==========================================================

def normalize_result(
    result,
    merchant_id
):

    if result is None:

        return None

    if not isinstance(
        result,
        dict
    ):

        return {
            "merchant_id":
                merchant_id,

            "decision":
                "ERROR",

            "reason":
                "RevenueOS-AI returned an invalid result format."
        }


    if not result.get(
        "merchant_id"
    ):

        result["merchant_id"] = (
            merchant_id
        )


    if not result.get(
        "decision"
    ):

        result["decision"] = (
            "UNKNOWN"
        )


    reason = result.get(
        "reason"
    )


    if (
        reason is None
        or str(reason).strip() == ""
        or str(reason).strip().lower()
        in [
            "none",
            "no reason provided"
        ]
    ):

        result["reason"] = (
            generate_reason(result)
        )


    if "failure_rate" in result:

        try:

            result["failure_rate"] = float(
                result["failure_rate"]
            )

        except (
            TypeError,
            ValueError
        ):

            pass


    if "risk_score" in result:

        try:

            result["risk_score"] = round(
                float(
                    result["risk_score"]
                ),
                2
            )

        except (
            TypeError,
            ValueError
        ):

            pass


    return result


# ==========================================================
# CASE DATABASE
# ==========================================================

def normalize_case(case):
    if not isinstance(case, dict):
        return {}

    normalized = dict(case)

    normalized.setdefault("review_id", None)
    normalized.setdefault("review_status", "N/A")
    normalized.setdefault("reviewer", None)
    normalized.setdefault("review_decision", None)
    normalized.setdefault("review_comments", None)
    normalized.setdefault("updated_at", normalized.get("created_at"))

    normalized["merchant_id"] = str(normalized.get("merchant_id", ""))
    normalized["case_id"] = str(normalized.get("case_id", ""))
    normalized["status"] = str(normalized.get("status", "UNKNOWN"))
    normalized["recommended_action"] = str(
        normalized.get("recommended_action", "UNKNOWN")
    )
    normalized["risk_category"] = str(
        normalized.get("risk_category", "Unknown")
    )

    try:
        normalized["risk_score"] = round(
            float(normalized.get("risk_score", 0)), 2
        )
    except (TypeError, ValueError):
        normalized["risk_score"] = 0.0

    try:
        normalized["confidence"] = float(
            normalized.get("confidence", 0)
        )
    except (TypeError, ValueError):
        normalized["confidence"] = 0.0

    return normalized


def normalize_cases(cases):
    return [
        normalize_case(case)
        for case in cases
        if isinstance(case, dict)
    ]


@app.get(
    "/cases"
)
def cases():

    try:

        all_cases = get_all_cases()
        normalized_cases = normalize_cases(all_cases)

        return {
            "count": len(normalized_cases),
            "cases": normalized_cases
        }

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Case retrieval error: "
                f"{type(e).__name__}: {e}"
            )
        )


# ==========================================================
# STORED CASE BY ID
# ==========================================================

@app.get(
    "/cases/{case_id}"
)
def stored_case(
    case_id: str
):

    try:

        all_cases = normalize_cases(
            get_all_cases()
        )

        for case in all_cases:

            if case.get("case_id") == case_id:
                return case

        raise HTTPException(
            status_code=404,
            detail=f"Case {case_id} was not found."
        )

    except HTTPException:
        raise

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Case retrieval error: "
                f"{type(e).__name__}: {e}"
            )
        )


# MERCHANT RISK INVESTIGATION
# ==========================================================

@app.get(
    "/merchant/{merchant_id}"
)
def merchant_risk(
    merchant_id: str
):

    try:

        result = run_revenueos(
            merchant_id
        )

        if result is None:

            raise HTTPException(
                status_code=404,
                detail=(
                    f"No result returned for "
                    f"merchant {merchant_id}."
                )
            )


        result = normalize_result(
            result,
            merchant_id
        )


        return result


    except HTTPException:

        raise


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Agent error: "
                f"{type(e).__name__}: {e}"
            )
        )


# ==========================================================
# APPROVE REVIEW
# ==========================================================

@app.post(
    "/review/{review_id}/approve"
)
def approve_review(
    review_id: str,
    request: ReviewDecisionRequest
):

    try:

        result = process_review_decision(
            merchant_id=request.merchant_id,
            review_id=review_id,
            review_decision="APPROVE",
            reviewer=request.reviewer,
            comments=request.comments
        )

        return result


    except ValueError as e:

        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Review processing error: "
                f"{type(e).__name__}: {e}"
            )
        )


# ==========================================================
# REJECT REVIEW
# ==========================================================

@app.post(
    "/review/{review_id}/reject"
)
def reject_review(
    review_id: str,
    request: ReviewDecisionRequest
):

    try:

        result = process_review_decision(
            merchant_id=request.merchant_id,
            review_id=review_id,
            review_decision="REJECT",
            reviewer=request.reviewer,
            comments=request.comments
        )

        return result


    except ValueError as e:

        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Review processing error: "
                f"{type(e).__name__}: {e}"
            )
        )


# ==========================================================
# HOLD REVIEW
# ==========================================================

@app.post(
    "/review/{review_id}/hold"
)
def hold_review(
    review_id: str,
    request: ReviewDecisionRequest
):

    try:

        result = process_review_decision(
            merchant_id=request.merchant_id,
            review_id=review_id,
            review_decision="HOLD",
            reviewer=request.reviewer,
            comments=request.comments
        )

        return result


    except ValueError as e:

        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Review processing error: "
                f"{type(e).__name__}: {e}"
            )
        )


# ==========================================================
# API INFORMATION
# ==========================================================

@app.get(
    "/api/info"
)
def api_info():

    return {

        "name":
            "RevenueOS-AI",

        "version":
            "1.0.0",

        "architecture": [

            "Risk Assessment",

            "Decision Agent",

            "Investigation Agent",

            "Evidence Analyzer",

            "Confidence Scorer",

            "Action Policy",

            "Human Review Controller",

            "Audit Logger",

            "Case Manager"

        ],

        "review_endpoints": [

            "POST /review/{review_id}/approve",

            "POST /review/{review_id}/reject",

            "POST /review/{review_id}/hold"

        ],

        "case_endpoints": [

            "GET /cases"

        ],

        "status":
            "operational"
    }


# ==========================================================
# LOCAL TEST
# ==========================================================

if __name__ == "__main__":

    print("=" * 70)

    print(
        "REVENUEOS-AI API"
    )

    print("=" * 70)

    print("\nAPI endpoints:")

    print(
        "GET  /"
    )

    print(
        "GET  /health"
    )

    print(
        "GET  /merchant/{merchant_id}"
    )

    print(
        "GET  /cases"
    )

    print(
        "POST /review/{review_id}/approve"
    )

    print(
        "POST /review/{review_id}/reject"
    )

    print(
        "POST /review/{review_id}/hold"
    )

    print(
        "GET  /api/info"
    )